"""add_index_to_deleted_at_fields

Revision ID: 27480d37fafe
Revises: 733dc07bf814
Create Date: 2026-05-11 11:15:44.527137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '27480d37fafe'
down_revision = '733dc07bf814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    photo_indexes = {index['name'] for index in inspector.get_indexes('photos')}
    target_indexes = {index['name'] for index in inspector.get_indexes('project_targets')}
    if op.f('ix_photos_deleted_at') not in photo_indexes:
        op.create_index(op.f('ix_photos_deleted_at'), 'photos', ['deleted_at'], unique=False)
    if op.f('ix_project_targets_deleted_at') not in target_indexes:
        op.create_index(op.f('ix_project_targets_deleted_at'), 'project_targets', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_targets_deleted_at'), table_name='project_targets')
    op.drop_index(op.f('ix_photos_deleted_at'), table_name='photos')
    # ### end Alembic commands ###
