"""add_soft_delete_to_project_targets

Revision ID: 733dc07bf814
Revises: c999b10b8b99
Create Date: 2026-05-08 17:06:07.763651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733dc07bf814'
down_revision = 'c999b10b8b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_targets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_targets', 'deleted_at')
    # ### end Alembic commands ###
