"""add_unique_constraints

Revision ID: c999b10b8b99
Revises: d1caa1136ef3
Create Date: 2026-05-08 16:37:46.980616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c999b10b8b99'
down_revision = 'd1caa1136ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_photo_display_id', 'photos', ['project_id', 'display_id'])
    op.create_unique_constraint('uq_project_target_name', 'project_targets', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_target_name', 'project_targets', type_='unique')
    op.drop_constraint('uq_project_photo_display_id', 'photos', type_='unique')
    # ### end Alembic commands ###
