"""add_folder_path_to_project_targets

Revision ID: d1caa1136ef3
Revises: e1118ac2c8c5
Create Date: 2026-05-08 16:28:22.947102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'd1caa1136ef3'
down_revision = 'e1118ac2c8c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    if not inspector.has_table('project_targets'):
        from app.database import Base
        import app.models  # noqa: F401

        Base.metadata.create_all(bind=bind)
        return

    columns = {column['name'] for column in inspector.get_columns('project_targets')}
    if 'folder_path' not in columns:
        op.add_column('project_targets', sa.Column('folder_path', sa.String(length=512), nullable=True, comment='NAS相对路径，用于照片自动关联'))

    indexes = {index['name'] for index in inspector.get_indexes('project_targets')}
    if op.f('ix_project_targets_folder_path') not in indexes:
        op.create_index(op.f('ix_project_targets_folder_path'), 'project_targets', ['folder_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_targets_folder_path'), table_name='project_targets')
    op.drop_column('project_targets', 'folder_path')
    # ### end Alembic commands ###
