"""add_folder_path_to_project_targets

Revision ID: d1caa1136ef3
Revises: e1118ac2c8c5
Create Date: 2026-05-08 16:28:22.947102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1caa1136ef3'
down_revision = 'e1118ac2c8c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_targets', sa.Column('folder_path', sa.String(length=512), nullable=True, comment='NAS相对路径，用于照片自动关联'))
    op.create_index(op.f('ix_project_targets_folder_path'), 'project_targets', ['folder_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_targets_folder_path'), table_name='project_targets')
    op.drop_column('project_targets', 'folder_path')
    # ### end Alembic commands ###
